version: "3.8"
services:
  mongo:
    image: mongo:6.0.5
    container_name: mongo-5920
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ecomreact_5920-volume:/data/db
    ports:
      - "27018:27017"
    networks:
      - ecomreact_5920_net
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2
  vault:
    image: vault:1.13.3
    container_name: vault-5920
    ports:
      - "8200:8200"
    environment:
        VAULT_SERVER: "http://127.0.0.1:8200"
        VAULT_DEV_ROOT_TOKEN_ID: vault-geppetto-2021
    cap_add:
      - IPC_LOCK
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  authproxy:
    build: ../../../application/services/default_services/authproxy
    image: authproxy-5920
    container_name: authproxy-5920
    ports:
      - "0000:8001"
    env_file: .env
    depends_on:
      - mongo
      - gcam
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  securitymanager:
    build: ../../../application/services/default_services/securitymanager
    image: securitymanager-5920
    container_name: securitymanager-5920
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  systemcredentialmanager:
    build: ../../../application/services/default_services/systemcredentialmanager
    image: systemcredentialmanager-5920
    container_name: systemcredentialmanager-5920
    ports:
      - "8005:8005"
    env_file: .env
    depends_on:
      - mongo
      - vault
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  gepfilemanager:
    build: ../../../application/services/default_services/gepfilemanager
    image: gepfilemanager-5920
    container_name: gepfilemanager-5920
    ports:
      - "3015:3015"
    env_file: .env
    depends_on:
      - mongo
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  gcam:
    build: ../../../application/services/default_services/gcam
    image: gcam-5920
    container_name: gcam-5920
    ports:
      - "8007:8007"
    env_file: .env
    depends_on:
      - mongo
      - vault
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  apigateway:
    build: ../../../application/services/custom_services/apigateway
    image: apigateway-5920
    container_name: apigateway-5920
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - authproxy
      - securitymanager
      - systemcredentialmanager
      - systementry
      - products

    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  # elasticsearch:
  #   image: elasticsearch:8.13.0
  #   container_name: elasticsearch-5920
  #   restart: always
  #   environment:
  #     - cluster.name=elasticsearch
  #     - node.name=elasticsearch
  #     - discovery.seed_hosts=elasticsearch
  #     - cluster.initial_master_nodes=elasticsearch
  #     - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
  #     - network.host=0.0.0.0
  #     - xpack.security.enrollment.enabled=false
  #     - xpack.security.enabled=false
  #     - xpack.watcher.enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 262144 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
  #       hard: 262144
  #   volumes:
  #     - elasticsearch:/usr/share/elasticsearch/data
  #   expose:
  #     - 9200
  #   ports:
  #     - 9200:9200
  #     - 9600:9600 # required for Performance Analyzer
  #   networks:
  #     - ecomreact_5920_net

  # kibana:
  #   image: kibana:8.13.0
  #   container_name: kibana-5920
  #   restart: always
  #   ports:
  #     - 5601:5601
  #   expose:
  #     - "5601"
  #   networks:
  #     - ecomreact_5920_net
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #     ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  # fluentd:
  #   image: fluentd-5920
  #   build: ../../../application/services/default_services/fluentd/fluend
  #   volumes:
  #     - ../../../application/services/default_services/fluentd/conf:/fluentd/etc
  #   links:
  #     - "elasticsearch"
  #   restart: always
  #   container_name: fluentd-5920
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #   networks:
  #     - ecomreact_5920_net


  systementry: 
    build: ../../../application/services/custom_services/systementry
    image: systementry-5920
    container_name: systementry-5920
    ports: 
      - 8047:8047
    env_file: .env
    depends_on:
      - mongo
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2

  products: 
    build: ../../../application/services/custom_services/products
    image: products-5920
    container_name: products-5920
    ports: 
      - 8048:8048
    env_file: .env
    depends_on:
      - mongo
    networks:
      - ecomreact_5920_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 0.0.0.0:24224
        fluentd-async-connect: "true"
        tag: fluent
    mem_limit: 300m
    mem_reservation: 150m
    cpus: 0.2


volumes:
  ecomreact_5920-volume:
    driver: local
  elasticsearch:
networks:
  ecomreact_5920_net:
    external: true
